apiVersion: apps/v1
kind: Deployment
metadata:
  name: wils-app
  namespace: dev
  labels:
    app: wils-app
spec:
  selector:
    matchLabels:
      app: wils-app
  template:
    metadata:
      labels:
        app: wils-app
    spec:
      containers:
      - name: wils-app
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: svc-wils-app
spec:
  selector:
    app: wils-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8888
